config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :areas

  resources :unities do
    resources :drivers
  end

  resources :customers
  devise_for :users

  resources :home, only: [:index]
  root to: 'home#index'  
  
end

app/models/unity.rb
require 'carrierwave/mongoid'
class Unity
  include Mongoid::Document
  
  field :prefix, type: Integer
  field :owner_name
  field :owner_email
  field :owner_phone
  field :document
  field :car_model
  field :license
  field :color
  field :active, type: Mongoid::Boolean, default: false
  field :qrx, type: Mongoid::Boolean, default: false


  mount_uploader :avatar, AvatarUploader
  validates_presence_of :prefix, :owner_name, :document, :car_model, :license
  embeds_many :drivers
end

app/controllers/unities_controller.rb
class UnitiesController < ApplicationController
  before_action :set_unity, only: [:show, :edit, :update, :destroy]

  # GET /unities
  # GET /unities.json
  def index
    @unities = Unity.all
  end

  # GET /unities/1
  # GET /unities/1.json
  def show
  end

  # GET /unities/new
  def new
    @unity = Unity.new
  end

  # GET /unities/1/edit
  def edit
  end

  # POST /unities
  # POST /unities.json
  def create
    @unity = Unity.new(unity_params)

    respond_to do |format|
      if @unity.save
        format.html { redirect_to @unity, notice: 'Unity was successfully created.' }
        format.json { render :show, status: :created, location: @unity }
      else
        format.html { render :new }
        format.json { render json: @unity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unities/1
  # PATCH/PUT /unities/1.json
  def update
    respond_to do |format|
      if @unity.update(unity_params)
        format.html { redirect_to @unity, notice: 'Unity was successfully updated.' }
        format.json { render :show, status: :ok, location: @unity }
      else
        format.html { render :edit }
        format.json { render json: @unity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unities/1
  # DELETE /unities/1.json
  def destroy
    @unity.destroy
    respond_to do |format|
      format.html { redirect_to unities_url, notice: 'Unity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unity
      @unity = Unity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unity_params
      params.require(:unity).permit(:prefix, :owner_name, :owner_email, :owner_phone, :document, :car_model, :avatar, :license, :color, :picture, :active, :qrx)
    end
end

app/helpers/unities_helper.rb
module UnitiesHelper
end

app/views/unities/_form.html.erb
<%= bootstrap_form_for @unity do |f| %>
<div class="col-md-2">
    <%= f.number_field :prefix, :min => 1  %>
</div>
<div class="col-md-6">
    <%= f.text_field :owner_name %>
</div>
<div class="col-md-4">
    <%= f.phone_field :owner_phone %>
</div>
<div class="col-md-4">
    <%= f.email_field :owner_email %>
</div>
<div class="col-md-3">
    <%= f.text_field :document %>
</div>
<div class="col-md-3">
    <%= f.text_field :car_model %>
</div>
<div class="col-md-3">
    <%= f.text_field :license %>
</div>
<div class="col-md-3">
    <%= f.color_field :color %>
</div>
<div class="col-md-4">
    <%= f.file_field :avatar %>
</div>
<div class="col-md-4">
    <%= f.check_box :active %>
</div>
<div class="col-md-4">
    <%= f.check_box :qrx %>
</div>
<br><br>
<div class="col-md-12">
    <%= f.submit :class => 'btn btn-primary' %>
</div>
<br><br>
<% end %>

app/views/unities/edit.html.erb
<h1>Editing Unity</h1>

<%= render 'form' %>

<%= link_to 'Show', @unity %> |
<%= link_to 'Back', unities_path %>

app/views/unities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Unities</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Prefix</th>
      <th>Car</th>
      <th>License</th>
      <th>Color</th>
      <th>Avatar</th>
      <th>Active</th>
      <th>Qrx</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unities.each do |unity| %>
      <tr>
        <td><%= unity.prefix %></td>
        <td><%= unity.car_model %></td>
        <td><%= unity.license %></td>
        <td><%= unity.color %></td>
        <td><%= unity.avatar %></td>
        <td><%= unity.active %></td>
        <td><%= unity.qrx %></td>
        <td><%= link_to 'Show', unity %></td>
        <td><%= link_to 'Edit', edit_unity_path(unity) %></td>
        <td><%= link_to 'Destroy', unity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unity', new_unity_path %>

app/views/unities/new.html.erb
<h1>New Unity</h1>

<%= render 'form' %>

<%= link_to 'Back', unities_path %>

app/views/unities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prefix:</strong>
  <%= @unity.prefix %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @unity.owner_name %> - <%= @unity.owner_email %>
</p>

<p>
  <strong>Car:</strong>
  <%= @unity.car_model %>
</p>

<p>
  <strong>License:</strong>
  <%= @unity.license %>
</p>

<p>
  <strong>Color:</strong> <span style="width: 40px; display: inline-block; height: 40px; background:<%= @unity.color %>"></span> 
</p>

<p>
  <strong>Picture:</strong>
  <img src="<%= @unity.avatar %>" alt="">
</p>

<p>
  <strong>Acvite:</strong>
  <%= @unity.active %>
</p>

<p>
  <strong>Qrx:</strong>
  <%= @unity.qrx %>
</p>

<%= link_to 'Edit', edit_unity_path(@unity) %> |
<%= link_to 'Back', unities_path %>