config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :areas

  resources :unities do
    resources :drivers
  end

  resources :customers
  devise_for :users

  resources :home, only: [:index]
  root to: 'home#index'  
  
end

app/models/area.rb
class Area
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Geospatial
  field :title
  field :description
  field :center, type: Hash, spatial: true
  field :paths,	type: Hash, spatial: true  
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:title, :description, :paths, :center)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= bootstrap_form_for @area do |f| %>
    <%= f.text_field :title %>
    <%= f.text_field :center %>
    <%= f.text_area :description %>
    <%= f.text_field :paths %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Areas</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Center</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.title %></td>
        <td><%= area.description %></td>
        <td><%= area.center %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @area.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @area.description %>
</p>

<p>
  <strong>Center:</strong>
  <%= @area.center.to_s %>
</p>

<p>
  <strong>Paths:</strong>
  <%= @area.paths.to_s %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>