config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :areas

  resources :unities do
    resources :drivers
  end

  resources :customers
  devise_for :users

  resources :home, only: [:index]
  root to: 'home#index'  
  
end

app/models/driver.rb
class Driver
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  belongs_to :unity, index: true
  
  field :name
  field :avatar
  field :phone
  field :birth, type: Date
  field :document
  field :email

  embedded_in :unity, :inverse_of => :drivers
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # POST /drivers
  # POST /drivers.json
  def create
    @unity = Unity.find(params[:unity_id])
    @driver = @unity.drivers.create!(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @unity, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @unity }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name, :birth, :document, :email, :phone, :avatar)
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= bootstrap_form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>
      <ul>
      <% @driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">    
    <%= f.select :unity_id, options_from_collection_for_select(Unity.all, '_id', 'prefix'), :prompt => 'Selecione o prefixo' %>
  </div>
  <div class="field">    
    <%= f.text_field :name %>
  </div>
  <div class="field">    
    <%= f.file_field :avatar %>
  </div>
  <div class="field">    
    <%= f.text_field :phone %>
  </div>
  <div class="field">    
    <%= f.date_field :birth %>
  </div>
  <div class="field">    
    <%= f.text_field :document %>
  </div>
  <div class="field">    
    <%= f.email_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drivers</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth</th>
      <th>Document</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.birth %></td>
        <td><%= driver.document %></td>
        <td><%= driver.email %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form' %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @driver.phone %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @driver.birth %>
</p>

<p>
  <strong>Document:</strong>
  <%= @driver.document %>
</p>

<p>
  <strong>Email:</strong>
  <%= @driver.email %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>