config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :areas

  resources :unities do
    resources :drivers
  end

  resources :customers
  devise_for :users

  resources :home, only: [:index]
  root to: 'home#index'  
  
end

app/views/layouts/_main_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Navegação</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>      
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to t('layout.home'), controller: 'home', action: 'index' %></li>        
        <li class="<%= 'active' if current_page?(areas_path) %>"><%= link_to t('layout.areas'), controller: 'areas', action: 'index' %></li> 
        <li class="<%= 'active' if current_page?(customers_path) %>"><%= link_to t('layout.customers'), controller: 'customers', action: 'index' %></li>       
        <li class="<%= 'active' if current_page?(unities_path) %>"><%= link_to t('layout.unities'), controller: 'unities', action: 'index' %></li>       
        <li class="<%= 'active' if current_page?(orders_path) %>"><%= link_to t('layout.orders'), controller: 'orders', action: 'index' %></li>       
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="active">Sair</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>byTaxinow - Painel de controle</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap" class="container">
  <% if user_signed_in? %>
    <%= render 'layouts/main_menu' %>    
  <% end %>
<br><br><br>
    <div id="main">
      <% if flash[:status] == false %>
      <div class="alert alert-danger">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= flash[:alert] %>
      </div>
      <% end %>
        <%= yield %>

    </div><!--#main-->
  <!--#wrap-->
  <footer id="main-footer" class="container">
     <nav class="navbar navbar-default navbar-fixed-bottom">    
      <div class="container">
        byTaxinow - byLife Soluções Web <a href="mailto:contato@bytaxinow.com.br" class="pull-right">contato@bytaxinow.com.br</a>
      </div>
    </nav>
  </footer>
  <div class="modal fade" id="main-modal" tabindex="-1" role="dialog" aria-labelledby="byTaxinow" aria-hidden="true"></div>
</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html ng-app="bytaxiServer">
<head>
	<meta charset="utf-8">
	<title>Coopertau - byTaxiNow</title>
	<meta name="description" content="">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="icon" href="favicon.ico" type="image/x-icon" />
	<script type="text/javascript" src="http://maps.google.com/maps/api/js"></script>
	<%= stylesheet_link_tag    'front', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
</head>
<body ng-controller="AppController">
<!--[if lt IE 10]>
	<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div class="page-container">		
<!-- START PAGE SIDEBAR -->
	<div class="page-sidebar">
		<!-- START X-NAVIGATION -->
		<ul class="x-navigation">
			<li class="xn-logo">
					<a ng-href="#/">byTaxiNow</a>
					<a ng-click="hideSidebar()" class="x-navigation-control"></a>
			</li>
			<li ng-show="!signedIn()" class="xn-profile">                        
					<div class="profile">                            
							<div class="profile-data">
									<div class="profile-data-name" ng-show="signedIn()">
									<%= link_to edit_user_registration_path do %>
										{{ user.email }}
									<% end %>
									</div>
							</div>                            
					</div>                                                                        
			</li>
			<li class="xn-title">Menu</li>
			<li ng-hide="signedIn()"><a href="#/login">Entrar</a></li>
			<li ng-class="{active : isActive('/')}"><a ng-href="#/"><span class="fa fa-desktop"></span> <span class="xn-text">Painel de controle</span></a></li>
			<li ng-class="{active : isActive('/calls')}"><a ng-href="#/calls"><span class="fa fa-sort-alpha-desc"></span> Central de Chamados</a></a></li>
			<li ng-class="{active : isActive('/maps')}"><a ng-href="#/maps"><span class="fa fa-map-marker"></span> P.A. Mapas</a></li>
			<li ng-class="{active : isActive('/customers')}"><a ng-href="#/customers"><span class="fa fa-users"></span> Clientes</a></li>
			<li ng-class="{active : isActive('/unities')}"><a ng-href="#/unities"><span class="fa fa-cab"></span> Cooperados</a></li>
			<li ng-class="{active : isActive('/lines')}"><a ng-href="#/lines"><span class="glyphicon glyphicon-sort "></span>Filas</a></li>
			<li ng-class="{active : isActive('/travels')}"><a ng-href="#/travels"><span class="fa fa-road"></span>Viagens</a></li>
			<li ng-class="{active : isActive('/closings')}"><a ng-href="#/closings"><span class="fa fa-folder-open"></span>Fechamentos</a></li>
			<li ng-class="{active : isActive('/settings')}"><a ng-href="#/settings"><span class="fa fa-gear"></span>Confgurações</a></li>
		</ul>
		<!-- END X-NAVIGATION -->
	</div>
	<!-- END PAGE SIDEBAR -->
	<!-- PAGE CONTENT -->
	<div class="page-content">
		<ul class="x-navigation x-navigation-horizontal x-navigation-panel">
			<!-- TOGGLE NAVIGATION -->
			<li class="xn-icon-button">
					<a ng-click="hideSidebar()" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
			</li>
			<!-- END TOGGLE NAVIGATION -->
			<!-- SEARCH -->
			<li class="xn-search">
					<form role="form">
							<input type="text" name="search" placeholder="Pesquisa..."/>
					</form>
			</li>   
			<!-- END SEARCH -->
			<!-- SIGN OUT -->
			<li ng-show="signedIn()" class="xn-icon-button pull-right">
			<a ng-click="logout()" class="mb-control"><span class="fa fa-sign-out"></span></a>				
			</li> 
			<!-- END SIGN OUT -->
		</ul>
		<div ng-view></div>
	</div>
	<!-- END PAGE CONTENT -->
</div>
</body>
</html>